### ISSUE TITLE
Tuning of MPC controller 

### ISSUE THREAD

**Issue by Thulasiram-29** [cord-burmeister/master3_nav#1]
Tuning of MPC controller is not performing well in terms of increasing min turning radius in Ackermann constraints , please look into it by trying increase the radius and perform the test simulation.

**Comment by cord-burmeister** [comment]
Hi, thanks for the feedback.

I was just experimenting with the different controller. I think the change set [b24dc34 "Fine Tune navigation" should improve the behavior, because i changed       # how much rotational variation is considered during trajectory sampling.
      wz_std: 1.8
      wz_std: 3.2.
      I that what you think ?
